CREATE OR REPLACE PROCEDURE REFRESH_PROC IS
	TEST NUMBER(1);
	BEGIN
		SELECT CNT INTO TEST FROM
			(SELECT COUNT(*) CNT FROM MY_SCHEMA.CONTROL_TABLE WHERE TABLE_NAME = 'MY_TABLE' AND
			REGEXP_SUBSTR(CONTROL_TABLE.COL,'[0-9]{4}-[0-9]{1,}-[0-9]{1,}')=TO_CHAR(SYSDATE,'YYYY-MM-DD'));
		IF TEST >=1
			THEN
			DBMS_MVIEW.REFRESH('MY_MVIEW'); /*Materialized view built from MY_TABLE*/
		END IF;
	END;