CREATE OR REPLACE PROCEDURE APPEND_PROC IS
BEGIN
INSERT INTO MY_SCHEMA.TEMP_TABLE
(SELECT * FROM MY_SCHEMA.MY_TABLE
WHERE 
	LOAD_ID IN 
		(SELECT LOAD_ID 
		FROM
			(SELECT DISTINCT RANK() OVER (ORDER BY MONTH_ID DESC, LOAD_ID DESC) AS NUM, LOAD_ID
			FROM 
				MY_SCHEMA.CONTROL_TABLE 
			WHERE 
				SIGNED_OFF = 'Y' AND TABLE_NAME = 'MY_TABLE')
		WHERE NUM=2)
	AND CASE_CLOSED_DATE < 
		(SELECT 
			MIN(CASE_CLOSED_DATE)
		FROM 
			MY_SCHEMA.MY_TABLE WHERE LOAD_ID IN 
				(SELECT LOAD_ID 
				FROM 
					(SELECT 
						DISTINCT RANK() OVER (ORDER BY MONTH_ID DESC, LOAD_ID DESC) AS NUM, LOAD_ID
					FROM 
						MY_SCHEMA.CONTROL_TABLE 
					WHERE 
						SIGNED_OFF = 'Y' AND TABLE_NAME = 'MY_TABLE')
				WHERE 
					NUM=1))
);
UPDATE MY_SCHEMA.MY_TABLE 
SET LOAD_ID = (SELECT LOAD_ID FROM
	(SELECT DISTINCT RANK() OVER (ORDER BY MONTH_ID DESC, LOAD_ID DESC) AS NUM, LOAD_ID
	FROM
		MY_SCHEMA.CONTROL_TABLE
	WHERE 
		SIGNED_OFF = 'Y' AND TABLE_NAME = 'MY_TABLE')
WHERE 
	NUM=1
);
INSERT INTO MY_SCHEMA.MY_TABLE SELECT * FROM MY_SCHEMA.TEMP_TABLE;
DELETE FROM MY_SCHEMA.TEMP_TABLE;
END;